### ISSUE TITLE
Uses of the distance.py

### ISSUE THREAD

**Issue by Irene-ML** [cuhk-seclab/SelectFuzz#14]
Hi, I realized that distance.py was only used in gen1.sh, but gen1.sh was not used in any other scripts. I assume this py file was only used for testing the functionality of the distance calculation, and its functionality has already been implemented in afl-llvm-pass.so.cc. Is my assumption right or the distance.py has other uses that I was not aware of?

**Comment by chluo911** [comment]
There are certain scripts or code that are not used by SelectFuzz. You could start investigating from the shell scripts at `/selectfuzz/scripts/fuzz/*.sh` since all the needed code is invoked from there. If gen1.sh is not used in /selectfuzz/scripts/fuzz/*.sh, it is not used in the main fuzzing process.
