### ISSUE TITLE
Problems Existing in Computing Instruction Probability in Loop

### ISSUE THREAD

**Issue by pjqwudi** [cuhk-seclab/SelectFuzz#3]
Kudos to your work first!
In the function find_pro that calculates the instruction probability in the source code, there are some doubts.
The source code is as follows:
```
   //it is the parent ins
   bool is_in = in_set.find(val) != in_set.end();
   if(is_in) {
     pro_map[val]=0;
     return;
   }
```
![CFG](https://github.com/cuhk-seclab/SelectFuzz/assets/39623822/f504410c-756e-4543-b6b5-461aea2e9095)
Specifically, the final calculation result of the instruction probability depends on the first instruction that is initially recursively calculated.
For example, starting recursive calculation from instruction A and instruction B, the distance value of the first node of the cycle will be completely different, and the probability may be 0. The emergence of this situation is due to the addition of data-dependent instructions in rel_ins. Will this affect the final distance calculation?
Looking forward to your reply!

**Comment by chluo911** [comment]
Thank you for the question.  I think even that the distance value of the first node (let's say C) is 0, this would not affect much the performance because node A (or B) has been instrumented. That is to say, once the execuiton visits A/B, it must has visited/will visit C. Therefore, the distance of C is that that important.
